<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sitl_dvrk_ros2</name>
  <version>0.0.0</version>
  <description>This package provides an interface for connecting to the dVRK console over ROS2, specifically modified for UIC SITL's da Vinci Robot.</description>
  <maintainer email="haeri.hsn@gmail.com">hossein</maintainer>
  <license>MIT</license>

  <!-- dependencies -->
  <depend>rclpy</depend>
  <!--<depend>sitl_dvrk_ros2_interfaces</depend> -->
  <depend>cisst_msgs</depend>
  <depend>cisst_ros_bridge</depend>
  <depend>cisst_ros_crtk</depend>
  <depend>crtk_msgs</depend>
  <depend>crtk_python_client</depend>
  <depend>dvrk_arms_from_ros</depend>
  <depend>dvrk_camera_registration</depend>
  <depend>dvrk_config</depend>
  <depend>dvrk_hrsv_widget</depend>
  <depend>dvrk_model</depend>
  <depend>dvrk_python</depend>
  <depend>dvrk_robot</depend>
  <depend>dvrk_video</depend>


  <export>
    <build_type>ament_python</build_type>
  </export>
</package>

